import Head from "next/head";
import MyDropzone from "@/components/Dropzone";
import { useStore } from "@/store";
import ShowPictures from "@/components/ShowPictures";

export default function Home() {
  const { originalImage } = useStore();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 flex flex-col gap-12 h-full pb-20">
        <header className="h-header border-b flex items-center">
          <img className="h-10" src="/svg/logo_light.svg" alt="App Logo" />
        </header>
        <div className=" mx-auto flex flex-col items-center gap-10">
          <div>
            <h1 className="text-5xl lg:text-6xl text-center font-bold">
              Restore any face photo
            </h1>
          </div>
          {originalImage ? (
            <ShowPictures />
          ) : (
            <MyDropzone className="w-full max-w-4xl h-56" />
          )}
        </div>
      </main>
    </>
  );
}
