import Head from "next/head";
import MyDropzone from "@/components/Dropzone";
import { useStore } from "@/store";
import ShowPictures from "@/components/ShowPictures";

export default function Home() {
  const { originalImage } = useStore();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-12 h-full pb-20">
        <div>
          <h1 className="text-5xl lg:text-6xl text-center font-bold">
            Restore any face photo
          </h1>
        </div>
        <div className="flex flex-col items-center gap-10">
          {originalImage ? (
            <ShowPictures />
          ) : (
            <MyDropzone className="w-full max-w-lg h-56" />
          )}
        </div>
      </div>
    </>
  );
}
